prefix champ-onto: <https://schema.champi40ns.eu#>
prefix champ-inst: <https://resource.champi40ns.eu/>

INSERT { 
    graph <https://data.champi40ns.eu/transport> {
		?new champ-onto:refersToLogTransport ?transport 
	}
}
where
{ 
    	BIND (URI(CONCAT(str(champ-inst:), "Transport/", str(?no))) as ?new)
        ?forest champ-onto:refersToTransport ?transport .

        {
            select ?no ?transport
            where {
                ?transport champ-onto:deliveryNo ?no . 
            } group by ?no ?transport
        }
    
}